# Generated by Django 4.1.3 on 2022-11-17 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0002_cofees'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cofees',
            new_name='Cofee',
        ),
    ]
